export const ADD_CITY = "ADD_CITY";
export const ADD_CITY_FAILURE = "ADD_CITY_FAILURE";

export const DELETE_CITY = "DELETE_CITY";
export const DELETE_CITY_FAILURE = "DELETE_CITY_FAILURE";

export const EDIT_CITY = "EDIT_CITY";
export const EDIT_CITY_FAILURE = "EDIT_CITY_FAILURE";

export const SIMILAR_CITIES_ARRIVED = "SIMILAR_CITIES_ARRIVED";
export const SIMILAR_CITIES_FAILURE = "SIMILAR_CITIES_FAILURE";

export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAILURE = "FETCH_CITIES_FAILURE";

export const DURING_ACTION = "DURING_ACTION";

export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
