export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_ERROR = "FETCH_ERROR";
export const WEATHER_RECEIVED = "WEATHER_RECEIVED";


export const ADD_CITY = "ADD_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const EDIT_CITY = "EDIT_CITY";
export const LOOK_FOR_SIMILAR_CITIES = "LOOK_FOR_SIMILAR_CITIES";
export const SIMILAR_CITIES_ARRIVED = "SIMILAR_CITIES_ARRIVED";
export const ACCEPT_CITY = "ACCEPT_CITY_REQUEST";

export const SAVE_CITIES_SUCCES = "SAVE_CITIES_ERROR";
export const SAVE_CITIES_ERROR = "SAVE_CITIES_SUCCES";
export const FETCH_CITIES_SUCCES = "FETCH_CITIES_SUCCES";
export const FETCH_CITIES_ERROR = "FETCH_CITIES_ERROR";
export const SAVE_CITIES_TO_DB = "SAVE_CITIES_TO_DB";
export const GET_CITIES_FROM_DB = "GET_CITIES_FROM_DB";
